### ISSUE TITLE
How to see "relations" between merged/split systems in csv and sqlite output?

### ISSUE THREAD

**Issue by cclopes** [uba/tathu#8]
As far as I could understand, a `relations` column is created in `systems` but is not saved in csv and spatialite outputs, only PostGIS, right?

It would be important to have this information on all types of outputs to be able to analyze the full lifecycle of these more complex systems.

**Comment by uba** [comment]
Hi @cclopes!

You are correct. Currently, only PostGIS IO implementation saves ``relations`` information.
We will include this option in other formats (e.g. CSV, SpatiaLite, etc.).
This is important information for systems analysis.

Thanks!

**Comment by uba** [comment]
Hi @cclopes

I added the option in the CSV and SpatiaLite outputs.
Please can you perform a test. Any problem please let me know.

Thanks.

**Comment by cclopes** [comment]
Hi @uba! I did a few tests and the results look correct. I'll close the issue for now and reopen if I find something wrong. Thanks!
